### ISSUE TITLE
Error: Nuxt build error 

### ISSUE THREAD

**Issue by ronna** [rht-labs/fee-fe#26]
I am building fee-fe on Ubuntu 18.04 and getting the below error:

sudo  npm run build

> fee-fe@1.0.0 build /home/tux/fee-fe
> nuxt build

 WARN  mode option is deprecated. Please use ssr: true for universal mode or ssr: false for spa mode and remove mode from nuxt.config

 WARN  You are using a low quality icon, use icon png. See https://pwa.nuxtjs.org/icon/                       13:23:03

ℹ Parsed 39 files in 2,8 seconds                                                                @nuxt/content 13:23:07
ℹ Production build                                                                                            13:23:11
ℹ Bundling only for client side                                                                               13:23:11
ℹ Target: static                                                                                              13:23:11

 WARN  Components directory not found: ~/components/global                                                    13:23:11

✔ Builder initialized                                                                                         13:23:11
✔ Nuxt files generated                                                                                        13:23:11

✖ Client
  Compiled with some errors in 1.34m

Hash: 116701fa0cb8c331a05e
Version: webpack 4.44.2
Time: 80609ms
Built at: 10/01/2020 1:24:34 PM
                     Asset       Size  Chunks               Chunk Names
                143cf64.js   8.74 KiB       3  [immutable]  pages/_slug
                2bcb806.js   5.52 KiB       2  [immutable]  content/plugin.js
                3546940.js   22.5 KiB       4  [immutable]  pages/catalog
                3810593.js   60.8 KiB       0  [immutable]  app
                565569a.js    190 KiB      11  [immutable]  vendors/pages/catalog
                60d0d21.js     93 KiB       9  [immutable]  vendors/content/plugin.js
                7d64eb5.js    177 KiB       1  [immutable]  commons/app
                9e670f0.js   1.35 KiB       6  [immutable]  pages/inspire
                  LICENSES  389 bytes
                a712c9f.js   2.39 KiB       7  [immutable]  runtime
                acab397.js   3.37 KiB       5  [immutable]  pages/index
                dee955d.js   22.2 KiB      10  [immutable]  vendors/pages/_slug
                e27cff1.js    244 KiB       8  [immutable]  vendors/app
                e852aee.js   4.43 KiB      12  [immutable]
img/defaultimg.1e85085.png      6 KiB
Entrypoint app = a712c9f.js 7d64eb5.js e27cff1.js 3810593.js

ERROR in ./node_modules/vuetify/src/styles/main.sass (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-1-1!./node_modules/postcss-loader/src??ref--6-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-1-3!./node_modules/vuetify/src/styles/main.sass)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Expected identifier.
   ╷
34 │         .v-application .blue-grey.#607d8b{
   │                                   ^
   ╵
  node_modules/vuetify/src/styles/generic/_colors.scss 34:35  @import
  node_modules/vuetify/src/styles/generic/_index.scss 2:9     @import
  /home/tux/fee-fe/node_modules/vuetify/src/styles/main.sass 7:9                                                   root stylesheet
 @ ./node_modules/vuetify/src/styles/main.sass 4:14-194
 @ ./node_modules/vuetify/lib/presets/default/index.js
 @ ./node_modules/vuetify/lib/services/presets/index.js
 @ ./node_modules/vuetify/lib/services/index.js
 @ ./node_modules/vuetify/lib/framework.js
 @ ./.nuxt/vuetify/plugin.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./.nuxt/client.js

 FATAL  Nuxt build error                                                                                      13:24:34

  at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack-edge/dist/webpack.js:5502:21)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at async WebpackBundler.build (node_modules/@nuxt/webpack-edge/dist/webpack.js:5451:5)
  at async Builder.build (node_modules/@nuxt/builder-edge/dist/builder.js:5643:5)
  at async Object.run (node_modules/@nuxt/cli-edge/dist/cli-build.js:109:7)
  at async NuxtCommand.run (node_modules/@nuxt/cli-edge/dist/cli-index.js:2809:7)

   ╭─────────────────────────────╮
   │                             │
   │   ✖ Nuxt Fatal Error        │
   │                             │
   │   Error: Nuxt build error   │
   │                             │
   ╰─────────────────────────────╯

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fee-fe@1.0.0 build: `nuxt build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fee-fe@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tux/.npm/_logs/2020-10-01T11_24_34_672Z-debug.log

**Comment by ronna** [comment]
I finally managed to run it on Windows
